name: Rust Static Build (AMD64)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Static Binary
    runs-on: ubuntu-latest
    # 使用专门针对 musl 静态编译优化的 Docker 镜像
    # 该镜像预装了 musl gcc 和 openssl 静态库
    container:
      image: messense/rust-musl-cross:x86_64-musl

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-app-amd64-static
        path: target/x86_64-unknown-linux-musl/release/你的项目名称
